APT::FTPArchive::Release::Origin "Pillars";
APT::FTPArchive::Release::Label "Pillarium Apt Repository";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "all amd64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Pillarium window manager packages";